/// Event enum.
#[derive(Debug, Clone)]
pub enum Event {
    /// Mouse cursor enters window area.
    MouseEnter,

    /// Mouse cursor leaves window area.
    MouseLeave,

    /// Mouse button press / release.
    MouseButton {
        state: ElementState,
        button: MouseButton,
    },

    /// Mouse move.
    MouseMove { position: Position },

    /// Mouse scroll wheel rolled or touchpad scroll gesture.
    ScrollWheel { delta: ScrollDelta },

    // Key pressed/released.
    KeyEvent {
        state: ElementState,
        keycode: Option<Keycode>,
        is_repeat: bool,
        modifiers: KeyModifiers,
        text: Option<String>,
    },
}

/// Element state.
#[derive(Debug, Copy, Clone)]
pub enum ElementState {
    Pressed,
    Released,
}

/// Mouse button enumeration.
#[derive(Debug, Copy, Clone)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Other(u8),
}

/// Position.
#[derive(Debug, Copy, Clone)]
pub struct Position {
    pub x: f32,
    pub y: f32,
}

/// Scroll delta enum.
#[derive(Debug, Copy, Clone)]
pub enum ScrollDelta {
    /// Amount of lines to scroll horizontally and vertically.
    /// This is generated by mouse wheel.
    LineDelta(f32, f32),

    /// Amount of pixels to scroll horizontally and vertically.
    /// This is generated by touchpad.
    PixelDelta(f32, f32),
}

#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Keycode {
    Esc,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    PrintScreen,
    ScrollLock,
    Pause,
    Insert,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,
    Left,
    Right,
    Up,
    Down,
    Backspace,
    Tab,
    CapsLock,
    Enter,
    LShift,
    RShift,
    LCtrl,
    RCtrl,
    LAlt,
    RAlt,
    LWin,
    RWin,
    NumLock,
}

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct KeyModifiers {
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub win: bool,
    pub keypad: bool,
}
